// Generated by 'unplugin-auto-import'
export {}
declare global {
  const appRouter: typeof import('./src/routes/app.router')['appRouter']
  const baseUrl: typeof import('./src/utils/constants')['baseUrl']
  const createContext: typeof import('./src/trpc/createContext')['createContext']
  const createRouter: typeof import('./src/trpc/createRouter')['createRouter']
  const createUserSchema: typeof import('./src/schemas/user.schema')['createUserSchema']
  const decode: typeof import('./src/utils/base64')['decode']
  const encode: typeof import('./src/utils/base64')['encode']
  const endpoint: typeof import('./src/utils/constants')['endpoint']
  const requestOtpSchema: typeof import('./src/schemas/user.schema')['requestOtpSchema']
  const routeErrorHandler: typeof import('./src/routes/errorHandler')['routeErrorHandler']
  const sendLoginEmail: typeof import('./src/utils/nodemailer')['sendLoginEmail']
  const signJwt: typeof import('./src/utils/jwt')['signJwt']
  const userRouter: typeof import('./src/routes/user.router')['userRouter']
  const verifyJwt: typeof import('./src/utils/jwt')['verifyJwt']
  const verifyOtpSchema: typeof import('./src/schemas/user.schema')['verifyOtpSchema']
}
